service: job-pushnotification-logger
frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x

functions:
  job-pushnotification-logger:
    handler: handler.handler
    events:
      - http:
          path: /
          method: get
          cors: true
      - http:
          path: /{proxy+}
          method: any
          cors: true
plugins:
  - serverless-plugin-typescript
  - serverless-offline
package:
  exclude:
    - node_modules/**
    - venv/**